### ISSUE TITLE
Firefox doesn't handle number input types well.

### ISSUE THREAD

**Issue by lgarron** [cubing/mark2#128]
From Sébastien: "When I click into a textfield of an event and delete the number in there, then immidiately "NaN" appears and I can't just enter another number. You should better allow empty fields and handle them as zeros."

Confirmed. I don't know what to do about this, because the browser is _supposed_ to do this correctly on its own.

There's probably a hack with reasonable tradeoffs.

**Comment by MLSTRM** [comment]
Same thing happens on IE9.

Its probably this: scramble.changeNumRounds("X", parseInt(this.value));
Maybe when empty, recieves a null value, so throws an error?

**Comment by lgarron** [comment]
That should fix it. If you delete all the text in Firefox, it just won't do anything until you start typing a new digit.
