### ISSUE TITLE
IE and Firefox 3.6 compatibility.

### ISSUE THREAD

**Issue by lgarron** [cubing/mark2#21]
Apparently innerHTML of a tbody is read-only sometimes. http://stackoverflow.com/questions/555965/javascript-replace-innerhtml-throwing-unknown-runtime-error

**Comment by lgarron** [comment]
I don't think this is worth the development time for a project like this.
Every delegate/organizer should have access to recent versions of Chrome, Firefox, Safari, or Opera, and those browsers should work just fine (and fast).

If anyone submits relatively non-intrusive fixes for IE and Firefox 3.6, I'd be happy take patches.

**Comment by MLSTRM** [comment]
I'll have a look into this.
Will fork for now.

**Comment by MLSTRM** [comment]
Just an update, Currently there is no way to do this. IE and old versions of firefox do not support webworkers so the rest breaks down. IE10 will in theory, but since its win8 only, there is no real way to test that currently.

**Comment by lgarron** [comment]
No way to do what? Mark 2 has always worked without web workers.
Web workers just help prevent locking up the UI. But I've made sure that Mark 2 can handle graceful degradation. Web workers support should not be an issue.

**Comment by MLSTRM** [comment]
Well I'll have another look at it. Webworkers are definitely not going to work, so I'll see why its still giving out errors. Also, the offline caching code at the start of scramble.js causes issues aswell. what's it currently being used for?

**Comment by lgarron** [comment]
[Offline caching](http://www.cubing.net/mark2-test/inc/offline.html).

You can remove the code or wrap it in

```
if (typeof window.applicationCache !== "undefined") {
  ...
}
```

EDIT: Replaced "null" with "undefined". Not sure why I typed the wrong thing.

**Comment by MLSTRM** [comment]
OK, thanks. does that code cause problems in any other browsers?
Also, the Square-1 scrambler now works in IE, but it took over 5 minutes. This could cause problems.

**Comment by lgarron** [comment]
I've added it at adbb7f7113aae36ef278352f8f7b639972b81297. It should be valid and (relatively) safe EMCAScript in all browsers, although I can't test it right now.

As for 5 minutes, I can't do much about that until I have new Square-1 code. That's one reason for me not to focus on supporting older browsers too much. Does everything else run (and in a reasonable time)?

**Comment by MLSTRM** [comment]
Everything else runs really quickly, its just the actual generation of sq1 scrabmles, not the initialization of it that runs slowly.

**Comment by MLSTRM** [comment]
Benchmark now runs in IE9, the Sq1 scrambler doesnt take as much time now either, little over a minute. The only problem is that to start it, the IE console needs to be open and the page refreshed. Not sure why this is.

If Classlist and webworkers are both HTML5/"new", surely if one works, the other won't, so Classlist can be avoided if there are no webworkers...

**Comment by lgarron** [comment]
Yeah, the commit above avoids classList if it doesn't exist (nothing should break).
(Feature detection for different features should be independent, though.)

Perhaps console.log only works in IE if the console is open, or something funny like that. I would test, except... I can't.
