### ISSUE TITLE
Create a standard event order.

### ISSUE THREAD

**Issue by lgarron** [cubing/mark2#29]
Object iteration is in arbitrary order, but it would be nice to have the order consistent among all browser. This just needs a reference array with the eventIDs in some order.

**Comment by jfly** [comment]
One ordering I've always liked is by best WCA single.
You could even group by puzzle, and then order by WCA single within each group.

**Comment by lgarron** [comment]
Order created in cefbf6a8a1c9cc150219662e6fcd885dada538cf. Current order is 2-7, then 3x3x3 events, then misc. Apart from NxNxN cubes, ti's the same order as the WCA results listings.
