### ISSUE TITLE
Define the mark2 interface for scramblers

### ISSUE THREAD

**Issue by lgarron** [cubing/mark2#6]
Methods and behaviour.

As of December 25, 2011:
- `version`
- `initialize(callback, randomSource, statusCallback)`
- `setRandomSource(src)`
- `getRandomScramble()`
- `drawScramble(parentElement, state, w, h)`

**Comment by jgouly** [comment]
drawScramble should take the element to draw into, not the parentElement.

**Comment by lgarron** [comment]
I'll think about it. Right now, I prefer `parentElement` because
- It allows both appending and replacing contents.
- It's what Raphael.js (the graphics library) does.
- I don't currently have a clean solution for allowing both (I don't just want to add arguments to the method willy-nilly).

**Comment by lgarron** [comment]
Interface/API defined in `inc/scramblers/README.md` in 6eb527d46a6f54b5e49f0f88710e8c27a44a4a14.

**Comment by lgarron** [comment]
Closing this issue because it is resolved.

Joey: See issue #102.
