### ISSUE TITLE
Profile the GWT 3x3x3 Javascript

### ISSUE THREAD

**Issue by lgarron** [cubing/mark2#63]
Remove unneeded methods.

**Comment by cs0x7f** [comment]
http://cubesolver.sinaapp.com/mark2/inc/scramblers/scramble_333.js
I've removed some of unneeded methods, check if it works~

**Comment by lgarron** [comment]
It seems to work just fine. :-)
(And wow, that's a lot of unneeded code.)

I'm going to leave this ticket open, though, because there are probably a few more things that can be optimized.

**Comment by cs0x7f** [comment]
update scramble_333.js again. I've removed almost all of unneeded codes.

**Comment by lgarron** [comment]
Cool, it seems to be even faster now. (<30ms mean, <20ms median per scramble.)

I've also went through and replaced all the == with === (throughout the project) in commit edf4bd14c38a48adbf877d721b00a472651bd936. I'm adding those changes to your updated code.

**Comment by lgarron** [comment]
Also, thanks for putting in the callbacks during initialization. I was thinking about doing that myself, so that it's easier to figure out how fast the initialization is going in a slow browser.
See 5e02637efa7e870b9b4baa092cfcb2716aeec2df for my changes to that.

**Comment by lgarron** [comment]
This is pretty much "fast enough" for now.
